export const homeObjectOne = {
    id: 'covid',
    linkOne: '/globe',
    linkTwo: '/usa',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Covid-19',
    headline: 'Interactive Map',
    description: 'Select either Global Map or USA Map to view corresponding COVID-19 Data.  Both maps are interactive allowing you to view up-to-date statistics and data.',
    buttonLabel: 'Global Map',
    buttonLabelTwo: 'USA Map',
    imgStart: false,
    img: require('../../images/covid1.jpg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false
}
export const homeObjectTwo = {
    id: 'tictactoe',
    linkOne: '/tictactoe',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Tic Tac Toe Inception',
    headline: 'Friendly Game of Ultimate Tic Tac Toe',
    description: 'While visitng our page, you can play a friendly game of Ultimate Tic Tac Toe and test your skills against friends.',
    buttonLabel: 'T^3 Game',
    imgStart: false,
    img: require('../../images/covid2.jpg'),
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true
}
export const homeObjectThree = {
    id: 'about',
    linkOne: '/aboutUs',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Us',
    headline: 'Boise State Senior Design Group',
    description: 'Payton Elsy, Kass Adams, Van Nguyen, Alex Acevedo',
    buttonLabel: 'Profiles',
    imgStart: false,
    img: require('../../images/covid4.jpg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false
}